### ISSUE TITLE
date_folder missing trailing zeros

### ISSUE THREAD

**Issue by mattdisco** [1Strategy/visualize-cur-using-glue-es#2]
The script generates the incorrect date_folder name, which results in a NoSuchKey S3 Exception.
Expected Value:
20180501-20180601
Actual Value:
2018501-2018601

line 155 should be something like:
```date_folder = str(now.year)+'{:02d}'.format(now.month)+"01-"+str(next_year)+'{:02d}'.format(next_month)+"01"```

**Comment by jing-1strategy** [comment]
Thanks for reporting the issue. Fixed and closing the issue.
