### ISSUE TITLE
report_folder should not include s3://bucket prefix

### ISSUE THREAD

**Issue by mattdisco** [1Strategy/visualize-cur-using-glue-es#3]
The report_folder is passed into the boto3 s3 client as a Prefix argument along with the source_bucket name.  

It should not include the s3:// or the bucket name.

This generates a KeyError: 'Contents'

The assignment of report_folder should be updated to not include ```"s3://" + source_bucket + "/" + ```

**Comment by jing-1strategy** [comment]
Thanks for reporting the issue. Fixed and closing the issue.
